# -*- coding: utf-8 -*-
"""Feb. 1, 2026.py (Assignment)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G6ge_g0JS70ppqhC0-6X3ojn00hX7jSp

#  Python Sets – Practice Questions

### Q1
Create a set from the list below and print only the unique values.

```python
data = [10, 20, 20, 30, 40, 40]
```
"""

data =[10,20,20,30,40,40]
data = set(data)
print(data)

"""### Q2
What will be the output? Explain why.

```python
s = {1, 2, 3, 3, 2}
print(s)
```
"""

s = {1,2,3,3,2}
print(s)

# because of s is a set, and a set is have only unique element, if there is any repeted elements then it will delete automatically.

"""### Q3
Create an empty set and add numbers from 1 to 5 using a loop.
"""

s = set()

for i in range(1,6):
  s.add(i)

print(s)

"""### Q4
Why does this code give an error? Fix it.

```python
s = {}
s.add(10)
```
"""

# s = {}
# s.add(10)
# because s creates a dictionary not a set, so this is why it make an error.

s = set()
s.add(10)
print(s)

"""### Q5
Given:
```python
A = {2, 4, 6, 8}
B = {4, 8, 12}
```
Find Union, Intersection, A-B
"""

A = {2, 4, 6, 8}
B = {4, 8, 12}

print('Intersecton is',A.intersection(B))

"""### Q6
Check whether 15 exists in the set {5, 10, 15, 20}.
"""

s = {5,10,15,20}

if 15 in s:
  print(True)

"""### Q7
Remove element 30 safely from {10, 20, 30, 40}.
"""

s = {10,20,30,40}
print('Before set is',s)
if 30 in s:
  s.remove(30)
print('After set is',s)

"""### Q8
Count unique elements in:
```python
nums = [1, 2, 2, 3, 4, 4, 5]
```
"""

nums = [1, 2, 2, 3, 4, 4, 5]

print('The length of unique elements is',len(set(nums)))

"""### Q9
What will be the output?
```python
s = {10, 20, 30}
s.add(20)
print(len(s))
```
"""

s = {10, 20, 30}
s.add(20)
print('The length of the given set after add 20 is',len(s))

"""### Q10
Can a set contain a list? Why?
```python
s = {1, 2, [3, 4]}
```
"""

s = {1, 2, [3, 4]}
# a set doesn't contain a list, because the elements of set are unique and there is no indexing system, that is, anyone not known about element indexing in a set, that why a set doesn't contain a set as well as a tuple,
# but a list have an indexing system, and also tuple have

"""### Q11
Convert {100, 200, 300} into list and print first element.
"""

s = {100, 200, 300}
print('The set is',s)
l = list(s)
print('The list is',l)
print('The first element of the list is',l[0])

"""### Q12
Students in two classes:
```python
class_A = {'Aman','Riya','Karan','Neha'}
class_B = {'Neha','Simran','Aman'}
```
"""

class_A = {'Aman','Riya','Karan','Neha'}
class_B = {'Neha','Simran','Aman'}

print('Total students in the class is',len(class_A.union(class_B)))

"""### Q13
Find unique characters in:
```python
text = 'programming'
```
"""

text1 = 'programming'
text = set(text1)
print(text)
print(len(text),'are unique elements present in',text1)

"""### Q14
Remove duplicate words from:
```python
sentence = 'python is easy and python is powerful'
```
"""

sentence = 'python is easy and python is powerful'
sentence = sentence.split()
print(sentence)

sentence = set(sentence)
print(sentence)

"""### Q15
What is the output?
```python
s = set('hello')
print(s)
```
"""

s = set('hello')
print(s)

# the output is only unique character, because set function converts it into unique characters