# -*- coding: utf-8 -*-
"""Feb. 3, 2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UdJwXLRHGhaQxirO9z8jq45VSN66yewO
"""

task_list =[]

while True:
  print('\n--- TO DO LIST ---')
  print('1. Add Task')
  print('2. View Tasks')
  print('3. Mark Task as Done')
  print('4. Delete Task')
  print('5. Exit')

  choice = input('Enter your choice: ')

  if choice == "1":
    new_task_name = input('Enter task name: ')
    task_list.append((new_task_name, 'Pending'))
    print('Task added')

  elif choice == "2":
    if len(task_list) == 0:
      print('No tasks available.')
    else:
      for i in range(len(task_list)):
        print(i+1, ".", task_list[i][0], "-", task_list[i][1])

  elif choice == "3":
    num = int(input('Enter task number: ')) -1
    if 0 <= num < len(task_list):
      task_list[num] = (task_list[num][0], 'Done')
      print('Task marked as done')
    else:
      print('Invalid task number.')

  elif choice == "4":
    num = int(input('Enter task number: ')) -1
    if 0 <= num < len(task_list):
      task_list.pop(num)
      print('Task deleted')
    else:
      print('Invalid task number.')

  elif choice == "5":
    print('Exiting To-Do List.')
    break

  else:
    print('Invalid choice. Try again.')