# -*- coding: utf-8 -*-
"""Jan. 3, 2026 (Assignment)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/180EqnYHUR7wH-m5AF-EvXQv3sHqbbfOb

# Python Variables Practice (Assignment 1)

**Topics Covered:**
- Variable creation
- int, float, str, bool data types
- Printing variables
- f-strings

## Section 1: Variable Creation & Printing

### Question 1
Create a variable to store your **age** and print it.
"""

age=24
print(age)

"""### Question 2
Create a variable to store the **price of a notebook** (can be a decimal value) and print it.
"""

price=512.36
print(price)

"""### Question 3
Create a variable to store your **first name** and print it.
"""

first_name='mukeem'
print(first_name)

"""### Question 4
Create a variable to store whether you have **completed today’s class** (True/False) and print it.
"""

complete_taday_class=True
print(complete_taday_class)

"""### Question 5
Create two variables:
- one to store the **number of classes attended**
- one to store the **average rating** (float)
Print both.
"""

number_of_classes_attended=10
average_rating=4.5
print(number_of_classes_attended)
print(average_rating)

"""## Section 2: Printing using f-strings

### Question 6
Create variables for **name** and **age** and print:
> My name is Rahul and I am 22 years old.
"""

name="Rahul"
age=22
print(f"My name is {name} and I am {age} years old.")

"""
### Question 7
Create variables for **item name** and **price** and print:
> The price of Pen is 10.5 rupees."""

item_name="Pen"
price=10.5
print(f'The price of {item_name} is {price} rupees')

"""### Question 8
Create variables for **batch name** and **class completed status** and print:
> Batch DA10 class completed status is True.
"""

batch_name='DA10'
class_completed_status=True
print(f'{batch_name} class completed status is {class_completed_status}')