# -*- coding: utf-8 -*-
"""jan. 19, 2026 (Assignment)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18b8LECcwxoNFGKjuInRgORVlBOStjt63

## Question 1 (Easy)

**Title:** Print 1 to 10

### Problem Statement:
Print numbers from 1 to 10 using a for loop.

### Approach:
Use `range(1, 11)` inside a `for` loop and print each value.
"""

for i in range(1,11):
  print(i)

"""## Question 2 (Easy)

**Title:** Sum of First N Numbers

### Problem Statement:
Take an integer N as input and find the sum of numbers from 1 to N.

### Approach:
Initialize sum = 0, loop from 1 to N, add each value to sum.

"""

n=int(input("Enter a number: "))
sum=0
for i in range(1,n+1):
  sum+=i
print(sum)

"""## Question 3 (Easy)

**Title:** Even Numbers from 1 to 50

### Problem Statement:
Print all even numbers between 1 and 50.

### Approach:
Loop from 1 to 50 and check `i % 2 == 0`.

"""

for i in range(1,51,2):
  if i%2==0:
    print(i)

"""## Question 4 (Easy)

**Title:** Count Multiples of 3

### Problem Statement:
Take N as input and count how many numbers between 1 and N are divisible by 3.

### Approach:
Use a counter variable and increment when `i % 3 == 0`.

"""

n=int(input())
count=0
for i in range(n+1):
  if i%3==0:
    count+=1
print(f'{count} numbers between 1 and {n} are divisible by 3')

"""## Question 5 (Easy)

**Title:** Multiplication Table

### Problem Statement:
Take a number as input and print its multiplication table from 1 to 10.

### Approach:
Loop from 1 to 10 and multiply with the input number.

"""

n=int(input())
for i in range(1,11):
  print(f'{n} x {i} = {n*i}')

"""## Question 6 (Easy)

**Title:** Factorial of a Number

### Problem Statement:
Take a number N as input and find its factorial.

### Approach:
Initialize fact = 1 and multiply values from 1 to N.

"""

n=int(input())
f=1
for i in range(1,n+1):
  f*=i
print(f'The factorial of {n} is {f}')

"""## Question 7 (Easy)

**Title:** Running Sum

### Problem Statement:
Take N as input and print the running sum from 1 to N.

### Approach:
Use a sum variable and update it in each iteration.

"""

n=int(input("Enter a number: "))
sum=0
for i in range(1,n+1):
  sum+=i
  print(f'The number is {i} and the sum is {sum}')

"""## Question 8 (Easy)

**Title:** Add 5 to Each Number

### Problem Statement:
Take N as input and add 5 to each number from 1 to N and print the result.

### Approach:
Loop from 1 to N and use shorthand `value += 5`.

"""

n=int(input("Enter a number: "))
sum=0
for i in range(1,n+1):
  sum+=i
  print(f'The result is {sum+5}')

"""## Question 9 (Easy)

**Title:** Count Even and Odd Numbers

### Problem Statement:
Take N as input and count how many even and odd numbers are there between 1 and N.

### Approach:
Use two counters and check with modulo operator.

"""

n=int(input())
count_even=0
count_odd=0
for i in range(1,n+1):
  if i%2==0:
    count_even+=1
  else:
    count_odd+=1
print(f'There are {count_even} even numbers and {count_odd} odd numbers')

"""## Question 10 (Easy)

**Title:** Squares from 1 to N

### Problem Statement:
Take N as input and print the square of each number from 1 to N.

### Approach:
Use `i * i` inside the loop.

"""

n=int(input())
for i in range(1,n+1):
  print(f'The square of {i} is {i*i}')

"""## Question 11 (Medium)

**Title:** Sum of Even and Odd Separately

### Problem Statement:
Take N as input and find the sum of all even numbers and all odd numbers between 1 and N.

### Approach:
Use two sum variables and check each number with modulo.

"""

n=int(input())
sum_even=0
sum_odd=0
for i in range(1,n+1):
  if i%2==0:
    sum_even+=i
  else:
    sum_odd+=i
print(f'The sum of even numbers is {sum_even} and the sum of odd numbers is {sum_odd} from 1 to {n}')

"""## Question 12 (Medium)

**Title:** Divisible by 3 and 5

### Problem Statement:
Take N as input and count how many numbers between 1 and N are divisible by both 3 and 5.

### Approach:
Use logical AND condition inside the loop.

"""

n=int(input())
count=0
for i in range(1,n+1):
  if i%3==0 and i%5==0:
    count+=1
print(f'Total count is {count}')

"""## Question 13 (Medium)

**Title:** Skip Multiples of 4

### Problem Statement:
Take N as input and print numbers from 1 to N but skip multiples of 4.

### Approach:
Use `continue` when the number is divisible by 4.

"""

n=int(input())
for i in range(1,n+1):
  if i%4==0:
    continue
    print(i)

"""## Question 14 (Medium)

**Title:** Find the Largest Number

### Problem Statement:
Take N as input and find the largest number between 1 and N using a loop.

### Approach:
Assume the first value as largest and update using `if`.

"""

n=int(input('take range: '))
m=[]
for i in range(n):
  a=int(input())
  m.append(a)
print(f'The maximum is {max(m)}')

"""## Question 15 (Medium)

**Title:** Power of a Number

### Problem Statement:
Take two numbers `a` and `b` as input and calculate `a` raised to the power `b` using a for loop.

### Approach:
Initialize result = 1 and multiply it `b` times.

"""

a=int(input('a = '))
b=int(input('b = '))
result=1
for i in range(b):
  result*=a
print(result)

"""## Question 16 (Hard)

**Title:** Check Prime Number

### Problem Statement:
Take a number as input and check whether it is prime or not.

### Approach:
Loop from 2 to N-1 and use `break` if divisible.

"""

n=int(input())
is_prime=True
for i in range(2,n-1):
  if n%i==0:
    is_prime=False
    print(f'{n} is not a prime number')
    break
if is_prime:
  print(f'{n} is a prime number')

"""## Question 17 (Hard)

**Title:** Prime Numbers Between 1 and N

### Problem Statement:
Take N as input and print all prime numbers between 1 and N.

### Approach:
Use nested loops and a flag variable for prime checking.

"""

n=int(input())
print(f'All primes between 1 and {n} are:')
for i in range(1,n+1):
  is_prime=True
  for j in range(2,i-1):
    if i%j==0:
      is_prime=False
      break
  if is_prime:
    print(i)

"""## Question 18 (Hard)

**Title:** First Number Divisible by 7 and 11

### Problem Statement:
Take N as input and find the first number between 1 and N that is divisible by both 7 and 11. Stop after finding it.

### Approach:
Use logical AND and stop the loop using `break`.

"""

n=int(input())
print(f'The first number between 1 and {n} that is divisible by both 7 and 11 are: ',end="")
for i in range(1,n+1):
  if (i%7==0 and i%11==0):
    print(i,end=" ")

"""## Question 19 (Hard)

**Title:** Number Pattern

### Problem Statement:
Take N as input and print a right-angled number pattern using nested loops.

Example:
1
12
123

### Approach:
Use an outer loop for rows and an inner loop for printing numbers.

"""

n=int(input('Enter the number of rows: '))
for i in range(1,n+1):
  for j in range(1,i+1):
    print(j,end=" ")
  print()