# -*- coding: utf-8 -*-
"""Jan. 31, 2025 (Assignment)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KkqRM2sBtPKuZ38XCs4rwNKc_kZL6g5y

# Python Practice: Tuple and Set (Practice Only)

This notebook contains **practice questions only** on **Tuples** and **Sets**.

Instructions:
- Questions are written in **text cells**
- Write your solution in the **code cell below each question**
- Do NOT use any advanced concepts

##  Tuple Practice Questions

### Question 1
Create a tuple of 5 integers and print it.
"""

tup1 = (1,2,3,4,5)
print(tup1)

"""### Question 2
Create a tuple with different data types (int, float, string, boolean) and print each element separately.
"""

tup2 = (2,3.14,'Hello',True)
print(tup2[0],type(tup2[0]))
print(tup2[1],type(tup2[1]))
print(tup2[2],type(tup2[2]))
print(tup2[3],type(tup2[3]))

"""### Question 3
Find the length of a tuple containing names of 4 students.
"""

names = ('sandeep','aditi','mukeem','sushil')
print(len(names))

"""### Question 4
Access and print the last element of a tuple.
"""

print(names)
print(names[-1])

"""### Question 5
Check whether an element exists in a tuple or not.
"""

print(names)
if 'sandeep' in names:
  print('True')
else:
  print('False')

"""### Question 6
Convert a tuple into a list.
"""

tup = (1,2,3,4,5)
print(tup,type(tup))
lst=list(tup)
print(lst,type(lst))

"""### Question 7
Convert a list into a tuple.
"""

lst = [1,2,3,4,5]
print(lst,type(lst))
tup = tuple(lst)
print(tup,type(tup))

"""### Question 8
Create a tuple with repeated values and count how many times an element appears.
"""

tup = ('apple','banana','cherry','apple','apple','banana')

for element in set(tup):
  print(f'{element}: {tup.count(element)} times')

"""### Question 9
Find the index of an element in a tuple.
"""

print(names)
print(names.index('mukeem'))

"""### Question 10
Demonstrate that tuples are immutable (cannot be changed).
"""

tup = (1,2,3,4)
tup[2] = 5
print(tup)