# -*- coding: utf-8 -*-
"""jan. 17, 2026 (Assignment)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14DynftP4ELRxDvyfAS8VFOPtmS7_1gAI

Q1. Print numbers from 1 to 20 using while loop.

Approach:
- Initialize a variable
- Use while condition
- Increment inside loop
"""

num=1
while num<=20:
  print(num)
  num+=1

"""Q2. Print even numbers till 50 using while loop.

Approach:
- Start from 2
- Increment by 2
- Stop at 50
"""

for i in range(2,51,2):
  print(i)

"""Q3. Print multiplication table of 5.

Approach:
- Initialize counter
- Multiply inside loop
"""

i=1
while i<=10:
  print(f'5 x {i} = {5*i}')
  i+=1

"""Q4. Find sum of numbers from 1 to n.

Approach:
- Take input n
- Add numbers in loop
"""

n=int(input())
i=1
sum=0
while i<=n:
  sum+=i
print(f'The sum is {sum}')

"""Q5. Reverse a number using while loop.

Approach:
- Extract last digit
- Build reversed number
"""

n=int(input())
rev=0
while n>0:
  rem=n%10
  rev=rev*10+rem
  n//=10
print(rev)

"""Q6. Count digits in a number.

Approach:
- Divide number by 10 repeatedly
- Count iterations
"""

n=int(input())
count=0
while n>0:
  n//=10
  count+=1
print(count)

"""Q7. Check if a number is palindrome.

Approach:
- Reverse number
- Compare with original
"""

n=int(input())
num=n
rev=0
while n>0:
  rem=n%10
  rev=rev*10+rem
  n//=10
if rev==num:
  print(f'{num} is a palindrome')

"""Q8. Guess the number game.

Approach:
- Use while loop
- Continue until correct guess
"""

correct_guess=6
while True:
  guess=int(input())
  if guess==correct_guess:
    print('Correct Guess')
    break

"""Submission link for this assignment -"""