# -*- coding: utf-8 -*-
"""Jan. 10, 2026 (Assignment)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X4rZ8ARlTRWAIfrSaH-ZclbA6fFfNjUZ

# Python Operators Practice Notebook

Each question is followed by its solution in the next code cell.
Difficulty level: Easy to Medium.

## Arithmetic Operators

Q1. Add two numbers a = 10 and b = 5.
"""

a=10
b=5
print(a+b)

"""Q2. Find the remainder when 17 is divided by 4."""

print(17%4)

"""Q3. Calculate 3 raised to the power 4."""

print(3**4)

"""## Assignment Operators

Q4. Assign 10 to x and add 5 to it using assignment operator.
"""

x=10
x+=5
print(x)

"""Q5. Assign 20 to y and multiply it by 2 using assignment operator."""

y=20
y*=2
print(y)

"""Q6. Assign 15 to z and subtract 7 using assignment operator."""

z=15
z-=7
print(z)

"""## Comparison Operators

Q7. Check if 10 is greater than 5.
"""

if 10 > 5:
  print("10 is greater than 5")

"""Q8. Check if 7 is equal to 9."""

if 7 == 9:
  print("7 is equal to 9")
else:
  print("7 is not equal to 9")

"""Q9. Check if 8 is not equal to 3."""

if 8 != 3:
  print("8 is not equal to 3")

"""## Logical Operators

Q10. Check if 5 > 2 and 10 > 3.
"""

if 5 > 2 and 10 > 3:
  print("5 is greater than 2 and 10 is greater than 3")

"""Q11. Check if 5 > 10 or 3 < 7."""

if 5 > 10 or 3 < 7:
  print("5 is greater than 10 or 3 is less than 7")

"""Q12. Use not operator on condition 10 > 5."""

if not 10 > 5:
  print("10 is not greater than 5")
else:
  print("No 10 is not greater than 5")

"""## Identity Operators

Q16. Check if a and b refer to the same object.
Let a = 10, b = 10.
"""

a=10
b=10
if a==b:
  print("a and b refer to the same object")

"""Q18. Compare identity of two variables c and d where c = d = 5."""

c=d=5
if c==d:
  print("c and d refer to the same object")

"""## Membership Operators

Q19. Check if 3 is present in the list [1,2,3,4].
"""

list=[1,2,3,4]
if 3 in list:
  print("3 is present in the list")

"""Q20. Check if 'a' is not present in the string 'python'."""

string='python'
if 'a' not in string:
  print("'a' is not present in the string")

"""Q21. Check if 10 is in the tuple (5, 10, 15)."""

tuple=(5,10,15)
if 10 in tuple:
  print("10 is in the tuple")